service: BB-hackathon-question

custom:
  defaultDomain: bb-xion.cybozu.com
  defaultAPIToken: zd3TxBZ2gcnqeYxh5SQWZIXjmfb1jNXHKc4CzvVJ
  defaultAppID: 156

provider:
  name: aws
  runtime: nodejs10.x
  stage: prod
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource:
        - "*"
  environment:
    KINTONE_DOMAIN: ${self:custom.defaultDomain}
    KINTONE_APITOKEN: ${self:custom.defaultAPIToken}
    KINTONE_APPID: ${self:custom.defaultAppID}

functions:
  func:
    handler: handler.main
    description: 「kintoneの認知状況」を確認するアンケート用
    events:
      - http:
          path: bbq
          method: post
          cors: true
    environment:
      FUNCTION_NAME: ${self:service}-${self:provider.stage}